USE [master]
GO

/****** Object:  Database [tradedb]    Script Date: 19.04.2018 11:30:14 ******/
CREATE DATABASE [tradedb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tradedb', FILENAME = N'C:\Program Files\Microsoft SQL Server\DB\Data\tradedb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tradedb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\DB\Data\tradedb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tradedb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tradedb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tradedb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tradedb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tradedb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tradedb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tradedb] SET ARITHABORT OFF 
GO

ALTER DATABASE [tradedb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tradedb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tradedb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tradedb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tradedb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tradedb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tradedb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tradedb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tradedb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tradedb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tradedb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tradedb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tradedb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tradedb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tradedb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tradedb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tradedb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tradedb] SET RECOVERY FULL 
GO

ALTER DATABASE [tradedb] SET  MULTI_USER 
GO

ALTER DATABASE [tradedb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tradedb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tradedb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tradedb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tradedb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tradedb] SET  READ_WRITE 
GO


USE [tradedb]
GO

/****** Object:  Table [dbo].[Positions]    Script Date: 19.04.2018 12:18:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Positions](
	[AccountId] [int] NOT NULL,
	[Money] [decimal](18, 0) NULL,
	[Instrument] [nchar](16) NULL,
	[Lot] [float] NULL,
	[LotNumber] [float] NULL,
	[Price] [float] NULL,
	[OpenCote] [float] NULL,
	[CloseCote] [float] NULL,
	[PositionState] [nchar](10) NULL,
	[PositionResult] [text] NULL,
 CONSTRAINT [PK_Positions] PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


